### ISSUE TITLE
issue with HTTP request

### ISSUE THREAD

**Issue by boxxxie** [ad2games/docker-rails#3]
`https://registry-1.docker.io/v2/ad2games/docker-rails/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4`

this is giving me a 401 error.

I'm using rkt, which may be the problem. when i go to the link in my browser i get the same error.

**Comment by dziemba** [comment]
I'm not sure what caused that. We're using the image on a daily basis and never had issues, but we're using docker. I've never tried rkt.

I just released a new version, can you try that one and see if the error still happens?

**Comment by dziemba** [comment]
Closing this. If the problem still exists, we can re-open it.
