### ISSUE TITLE
Error if no Postgres Gem added to gemfile

### ISSUE THREAD

**Issue by drummerroma** [ad2games/docker-rails#5]
The following code is generating startup error if Postgres gem is not added to gemfile:

`SECRET_KEY_BASE=noop DATABASE_URL=postgres://noop ; \`

**Comment by dziemba** [comment]
Sorry for the late reply and thanks for reporting this.

The issue has now been fixed as of version `2.4.1`, see https://github.com/ad2games/docker-rails/commit/2aba84e9bc9646ff34c22c400b477f28db4583f0

Please re-open this if you still have any issues. Thanks!
